In [1]:
import numpy as np

In [2]:
((4 + 5j) * (2 + 3j))**(1/2)

(2.8360882180593743+3.8785817486054355j)

In [3]:
dicto={'a':'name', 'b':'city', 'c':'occupation', 'd':'telephone', 'e':'status', 'f':'hobby', 'g':'salary'}

In [4]:
dicto['c']

'occupation'

In [5]:
for key, val in dicto.items(): # при зададени 2 елемента итерирацията е по ключ и съответната стойност
    print(key, val, end=' ')

a name b city c occupation d telephone e status f hobby g salary 

In [6]:
for it in dicto.items(): # при зададен 1 елемент итерирацията е по елемент от речника
    print(it, end=' ')

('a', 'name') ('b', 'city') ('c', 'occupation') ('d', 'telephone') ('e', 'status') ('f', 'hobby') ('g', 'salary') 

In [7]:
listo=[1,2,3,4,5,6,7,8,9]
for it in listo:
    it=it+1
    print(it, end=' ')

2 3 4 5 6 7 8 9 10 

In [8]:
listo # не се е изменил

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
a = np.array([1, 2, 3]) # даваме аргумента като списък, като всички елементи трябва да са от един и същи вид.

In [10]:
print(a)
print(type(a)) # numpy array
print(a.dtype) # тип на елементите в array
print('ndim = rank ',a.ndim) # attribute for getting the axes, i.e. the rank; с колко индекса е обектът
print('size = array length ', a.size) # attribute to know the array length
print('shape = the size of each dimension ', a.shape) # a tuple of N-positive integers = the size for each dimension

[1 2 3]
<class 'numpy.ndarray'>
int32
ndim = rank  1
size = array length  3
shape = the size of each dimension  (3,)


In [11]:
b = np.array([[1,2,3],[4,5,6]]) # аргументът е [списък от списък]=[ред1, ред2]

In [12]:
print(b) # елементите автоматично се подреждат подравнено
print('.ndim = rank =',b.ndim) # с колко индекса е обектът
print('.size = array length =', b.size) # брой на всички елементи
print('.shape = the size of each dimension =', b.shape) # (бр. редове, бр. стълбове)

[[1 2 3]
 [4 5 6]]
.ndim = rank = 2
.size = array length = 6
.shape = the size of each dimension = (2, 3)


In [13]:
c = np.array(((2,3,4),[5,6,7], (8,9,1))) # np.array() приема също tuples или смесени lists и tuples
c

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [14]:
d = np.array([[1,2,3],[4,5,6]], dtype=complex) # така можем да избегнем default на данните
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [15]:
np.zeros([3, 3]) # може и с ()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones([3, 3]) # може и с ()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arange(10) # същото е np.arange(0, 10) е редица от 0 до 9 с default стъпка 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(4, 10) # създаване на едномерен array посредством тази функция

array([4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0, 12, 3) # създава array от малко към по-голямо с определена стъпка

array([0, 3, 6, 9])

In [20]:
np.arange(0, 12).reshape(3, 4) # 3 реда, 4 стълба; за създаване на двумерен array трябва да използваме reshape()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
np.linspace(0,20,11) # array във вид на интервал с нач. точка, кр. точка, разделен на n-1 равни подинтервала

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [22]:
np.random.random(3) # създаване на array с произволни числа

array([0.19068849, 0.45789048, 0.16951958])

In [23]:
np.random.random((3,4)) # може също да бъде двумерен

array([[0.53688764, 0.12365853, 0.63182084, 0.43594281],
       [0.24846789, 0.31301281, 0.29755651, 0.40552487],
       [0.50940905, 0.41805232, 0.39649373, 0.52061111]])

In [24]:
b=np.array([4,5,6])
print(a+4) # инкрементен оператор a+=3, това променя array
print(a*4) # инкрементен оператор a *= 2
print(a+b) # element-wise, т.е. събират се по компоненти
print(a*b) # element-wise, т.е. умножават се по компоненти; това НЕ Е МАТРИЧНО ПРОИЗВЕДЕНИЕ

[5 6 7]
[ 4  8 12]
[5 7 9]
[ 4 10 18]


In [25]:
A = np.arange(0, 9).reshape(3, 3)
B = np.ones((3,3))
np.dot(A,B) # умножаване на матрици ред по стълб А dot B; МАТРИЧНО ПРОИЗВЕДЕНИЕ

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [26]:
A.dot(B) # алтернативен начин за записване

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [27]:
A.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [76]:
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
a = np.arange(1, 10) # Универсални функции ufunc действат върху array елемент по елемент и показват резултата в друг array
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]


In [30]:
### Aggregate Functions действат върху много елементи и показват един единствен резултат
print(a.sum()) # сумата на всички елементи
print(a.min())
print(a.std())

45
1
2.581988897471611


In [31]:
####### Slicing за еднорангови редове
print(a[1:9]) # елементите от [1] до [9]; само а[1] ще посочи втория елемент в array 
print(a[1:9:2]) # ще вземе елементите от [1] до [9], но през един! Стъпка 1 дава същия ред
print(a[::2])
# ако пропуснем първото число, то се подразбира да е 0; ако пропуснем второто число, то се подразбира да е макс индекс;
# ако пропуснем третото число, то се подразбира да е 1

[2 3 4 5 6 7 8 9]
[2 4 6 8]
[1 3 5 7 9]


In [38]:
### Slicing за редове два индекса
A[0,:] # дава първия ред на матрицата; 
A[:,0] # дава първия стълб на матрицата
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
C=np.arange(0, 16).reshape((4, 4))
C[0:2, 0:2] # дефинираме ако трябва да извадим подматрица
C[[0,2], 1:3] # индексите може да се посочат и чрез списъци

for row in C: # итерация; ако е посочен само една интерираща променлива, се итерира по редовете
    print(row)

for item in C.flat: # принтира всички елементи ред след ред
    print(item, end = ' ')

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 

In [56]:
# за прилагане на агрегирана функция върху всеки ред или всеки стълб поотделно използваме:
np.apply_along_axis(np.mean, axis=0, arr=C) # (функция, ос 0=стълб 1=ред, конкретен array); тук показва средното на всеки стълб
np.apply_along_axis(np.mean, axis=1, arr=C) # тук показва средното на всеки ред

## Можем да използваме apply_along_axis() с наша си функция
#def foo(x): return x/2

#np.apply_along_axis(foo, axis=1, arr=C) # няма значение дали оста е 0 или 1

array([ 1.5,  5.5,  9.5, 13.5])

In [72]:
C[C>9] # показва за кои елементи булевият израз е True
C>9
C.transpose() # не променя матрицата, а само показва транспонираната ѝ

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [74]:
Li = np.random.random(20)
#L = Li.reshape(5, 4) # създава нов array
Li.shape = (4, 5) # не създава нов обект, а променя стария
#Li.ravel() # можем да превърнем многорангов array в еднорангов
#Li.shape(20) # също "разплита" матрицата
Li

array([[0.8782354 , 0.52853416, 0.02567341, 0.81611712, 0.47883302],
       [0.99801745, 0.6942474 , 0.39142238, 0.70423157, 0.36236003],
       [0.66557922, 0.61396909, 0.5536028 , 0.69632321, 0.91578747],
       [0.92258798, 0.27054459, 0.12225774, 0.52660401, 0.32237085]])

In [93]:
Aa = np.ones((4, 4))
Bb = np.zeros((4, 4))
np.vstack((Aa, Bb)) # вертикално "съшиване"
np.hstack((Aa, Bb)) # хоризонтално "съшиване"

aa = np.array([0, 1, 2])
bb = np.array([3, 4, 5])
cc = np.array([6, 7, 8])
#np.column_stack((aa, bb, cc)) # използват се върху еднорангови array, за да създадат двурангови
np.row_stack((aa, bb, cc)) # транспонираната на column.stack(); ако се използва върху двурангови, е аналог на vstack и hstack


array([[1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0.]])

In [102]:
[Dd,Kk] = np.hsplit(C,2) # разрязване splitting на реда симетрично по широчина horizontal. Може и на повече от 2 части
#[Dd,Kk] = np.vsplit(C,4) # разрязване splitting на ред по височина vertical
(Dd, Kk) # по-обща функция, която разрязва на несиметрични части, е np.split()

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [114]:
## Някои общи положения
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = a.copy() # ако искаме да направим независимо копие на даден array; командата b = a не създава независимо копие
#A*B # Vectorization A_ij * B_ij = C_ij без сумиране по индекси; a_i * b_i = c_i
#aa+A # Broadcasting пример със събиране на еднорангов и двурангов масив

In [117]:
### Четене и записване във файл
tes_dat=np.array([2,4,6,8,10,12,14,16,18,20])
np.save("tes_dat", tes_dat)
np.load("tes_dat.npy")

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])